### PR TITLE
Add container id to published system properties

### PR DESCRIPTION
**Pull request by 2m**

### CODE REVIEW

**Comment by dariush-y** [comment]
@2m I dunno what's the use case here, since plugin already prints container ids during health-check process.

**Comment by 2m** [comment]
My use case is to stop a container while running integration tests and test resilience.

By making container IDs available I can use spotify's java docker client to stop the container by its id from a test.

**Comment by dariush-y** [comment]
The ideal case is to let the plugin itself manage the life-cycle, what I do normally is modularising my project to separate projects so each project contains its own `docker-compose` file,  in this way I don't encounter issues regarding lack of resource etc, and plugin manages the life-cycle for me.

But if your issue it's not resolvable by aforementioned solution, let's merge this.

**Comment by 2m** [comment]
I see. I am not sure my use-case can be solved by having different modules.

In more detail, I want to stop one container in the middle of an integration test and see how resilient the code under test is. Therefore I need to stop the container from the test code itself.

**Pull request merged**
